# Generated by Django 2.1.5 on 2019-12-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonks', '0002_stonk_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stonk',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stonk',
            name='score',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='stonk',
            name='value',
            field=models.FloatField(db_index=True),
        ),
    ]
