version: "3"
services:
  app:
    restart: always
    build: .
    command: "sh start.sh"
    volumes:
      - .:/code
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:5.6
    volumes:
      - "./mysql:/var/lib/mysql"
    ports:
      - "3333:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret123
      - MYSQL_DATABASE=django_app
      - MYSQL_USER=django_app
      - MYSQL_PASSWORD=django_app123
